/* tslint:disable */
/* eslint-disable */
/**
 * Football Standings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Get Standings Response
 * @export
 * @interface GetStandingsResponseBody
 */
export interface GetStandingsResponseBody {
    /**
     * Country Name
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    countryName?: string;
    /**
     * League ID
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    leagueId?: string;
    /**
     * League Name
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    leagueName?: string;
    /**
     * Team ID
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    teamId?: string;
    /**
     * Team Name
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    teamName?: string;
    /**
     * Overall League Position
     * @type {string}
     * @memberof GetStandingsResponseBody
     */
    overallLeaguePosition?: string;
}

/**
 * Check if a given object implements the GetStandingsResponseBody interface.
 */
export function instanceOfGetStandingsResponseBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetStandingsResponseBodyFromJSON(json: any): GetStandingsResponseBody {
    return GetStandingsResponseBodyFromJSONTyped(json, false);
}

export function GetStandingsResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStandingsResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countryName': !exists(json, 'country_name') ? undefined : json['country_name'],
        'leagueId': !exists(json, 'league_id') ? undefined : json['league_id'],
        'leagueName': !exists(json, 'league_name') ? undefined : json['league_name'],
        'teamId': !exists(json, 'team_id') ? undefined : json['team_id'],
        'teamName': !exists(json, 'team_name') ? undefined : json['team_name'],
        'overallLeaguePosition': !exists(json, 'overall_league_position') ? undefined : json['overall_league_position'],
    };
}

export function GetStandingsResponseBodyToJSON(value?: GetStandingsResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country_name': value.countryName,
        'league_id': value.leagueId,
        'league_name': value.leagueName,
        'team_id': value.teamId,
        'team_name': value.teamName,
        'overall_league_position': value.overallLeaguePosition,
    };
}

