/* tslint:disable */
/* eslint-disable */
/**
 * Football Standings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetStandingsResponseBody } from './GetStandingsResponseBody';
import {
    GetStandingsResponseBodyFromJSON,
    GetStandingsResponseBodyFromJSONTyped,
    GetStandingsResponseBodyToJSON,
} from './GetStandingsResponseBody';

/**
 * 
 * @export
 * @interface GetStandings200Response
 */
export interface GetStandings200Response {
    /**
     * 
     * @type {Array<GetStandingsResponseBody>}
     * @memberof GetStandings200Response
     */
    data: Array<GetStandingsResponseBody>;
}

/**
 * Check if a given object implements the GetStandings200Response interface.
 */
export function instanceOfGetStandings200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetStandings200ResponseFromJSON(json: any): GetStandings200Response {
    return GetStandings200ResponseFromJSONTyped(json, false);
}

export function GetStandings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStandings200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetStandingsResponseBodyFromJSON)),
    };
}

export function GetStandings200ResponseToJSON(value?: GetStandings200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetStandingsResponseBodyToJSON)),
    };
}

