name: Football API

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/{PROJECT_Number}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "gh-runner@{PROJECT_ID}.iam.gserviceaccount.com"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            us.gcr.io/{PROJECT_ID}/football-api
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: "https://us.gcr.io"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build Image
        run: docker build --tag=us.gcr.io/{PROJECT_ID}/football-api:latest .

      - name: Push Image
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us.gcr.io | docker push us.gcr.io/{PROJECT_ID}/football-api:latest
