name: Build Football API docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: PRODUCTION
    env:
      NEXT_PUBLIC_CONTENTFUL_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_SPACE: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE }}
      NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}
      NEXT_PUBLIC_CONTENTFUL_HOST: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_HOST }}
      NEXT_PUBLIC_ISSUER_URL: ${{ secrets.NEXT_PUBLIC_ISSUER_URL }}
      NEXT_PUBLIC_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_ID }}
      NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
      NEXT_PUBLIC_AUDIENCE: ${{ secrets.NEXT_PUBLIC_AUDIENCE }}

    steps:
      - uses: actions/checkout@v2

      - name: Create .env.production
        run: |
          echo "NEXT_PUBLIC_CONTENTFUL_TOKEN=${NEXT_PUBLIC_CONTENTFUL_TOKEN}" > .env.production
          echo "NEXT_PUBLIC_CONTENTFUL_SPACE=${NEXT_PUBLIC_CONTENTFUL_SPACE}" >> .env.production
          echo "NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}" >> .env.production
          echo "NEXT_PUBLIC_CONTENTFUL_HOST=${NEXT_PUBLIC_CONTENTFUL_HOST}" >> .env.production
          echo "NEXT_PUBLIC_ISSUER_URL=${NEXT_PUBLIC_ISSUER_URL}" >> .env.production
          echo "NEXT_PUBLIC_CLIENT_ID=${NEXT_PUBLIC_CLIENT_ID}" >> .env.production
          echo "NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}" >> .env.production
          echo "NEXT_PUBLIC_AUDIENCE=${NEXT_PUBLIC_AUDIENCE}" >> .env.production

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/{PROJECT_NUMBER}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "gh-runner@{PROJECT_ID}.iam.gserviceaccount.com"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            us.gcr.io/{PROJECT_ID}/football-website
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: "https://us.gcr.io"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build Image
        run: docker build --tag=us.gcr.io/{PROJECT_ID}/football-website:latest .

      - name: Push Image
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us.gcr.io | docker push us.gcr.io/{PROJECT_ID}/football-website:latest
